version: '3.8'

services:
  app:
    entrypoint:
    - sleep
    - infinity
    build:
      context: .
      dockerfile: Dockerfile.python
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    - ./:/app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: my_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: my_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  node:
    entrypoint:
      - sleep
      - infinity
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - ./:/node-app
    ports:
      - "3000:3000"

volumes:
  mysql_data:
  mongo_data:
