FROM node:22
WORKDIR /node-app

ENV TZ=America/Chicago
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update --fix-missing && \
    apt-get upgrade -y --fix-missing && \
    apt-get install -y git curl

COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000